/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSkillsIndexRouteImport } from './routes/api/skills/index'
import { Route as ApiInstallShRouteImport } from './routes/api/install/sh'
import { Route as ApiInstallCliRouteImport } from './routes/api/install/cli'
import { Route as ApiSkillsNameIndexRouteImport } from './routes/api/skills/$name/index'
import { Route as ApiSkillsNameFilesSplatRouteImport } from './routes/api/skills/$name/files/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsIndexRoute = ApiSkillsIndexRouteImport.update({
  id: '/api/skills/',
  path: '/api/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstallShRoute = ApiInstallShRouteImport.update({
  id: '/api/install/sh',
  path: '/api/install/sh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstallCliRoute = ApiInstallCliRouteImport.update({
  id: '/api/install/cli',
  path: '/api/install/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsNameIndexRoute = ApiSkillsNameIndexRouteImport.update({
  id: '/api/skills/$name/',
  path: '/api/skills/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsNameFilesSplatRoute = ApiSkillsNameFilesSplatRouteImport.update({
  id: '/api/skills/$name/files/$',
  path: '/api/skills/$name/files/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/install/cli': typeof ApiInstallCliRoute
  '/api/install/sh': typeof ApiInstallShRoute
  '/api/skills/': typeof ApiSkillsIndexRoute
  '/api/skills/$name/': typeof ApiSkillsNameIndexRoute
  '/api/skills/$name/files/$': typeof ApiSkillsNameFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/install/cli': typeof ApiInstallCliRoute
  '/api/install/sh': typeof ApiInstallShRoute
  '/api/skills': typeof ApiSkillsIndexRoute
  '/api/skills/$name': typeof ApiSkillsNameIndexRoute
  '/api/skills/$name/files/$': typeof ApiSkillsNameFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/install/cli': typeof ApiInstallCliRoute
  '/api/install/sh': typeof ApiInstallShRoute
  '/api/skills/': typeof ApiSkillsIndexRoute
  '/api/skills/$name/': typeof ApiSkillsNameIndexRoute
  '/api/skills/$name/files/$': typeof ApiSkillsNameFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/install/cli'
    | '/api/install/sh'
    | '/api/skills/'
    | '/api/skills/$name/'
    | '/api/skills/$name/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/install/cli'
    | '/api/install/sh'
    | '/api/skills'
    | '/api/skills/$name'
    | '/api/skills/$name/files/$'
  id:
    | '__root__'
    | '/'
    | '/api/install/cli'
    | '/api/install/sh'
    | '/api/skills/'
    | '/api/skills/$name/'
    | '/api/skills/$name/files/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiInstallCliRoute: typeof ApiInstallCliRoute
  ApiInstallShRoute: typeof ApiInstallShRoute
  ApiSkillsIndexRoute: typeof ApiSkillsIndexRoute
  ApiSkillsNameIndexRoute: typeof ApiSkillsNameIndexRoute
  ApiSkillsNameFilesSplatRoute: typeof ApiSkillsNameFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills/': {
      id: '/api/skills/'
      path: '/api/skills'
      fullPath: '/api/skills/'
      preLoaderRoute: typeof ApiSkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/install/sh': {
      id: '/api/install/sh'
      path: '/api/install/sh'
      fullPath: '/api/install/sh'
      preLoaderRoute: typeof ApiInstallShRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/install/cli': {
      id: '/api/install/cli'
      path: '/api/install/cli'
      fullPath: '/api/install/cli'
      preLoaderRoute: typeof ApiInstallCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills/$name/': {
      id: '/api/skills/$name/'
      path: '/api/skills/$name'
      fullPath: '/api/skills/$name/'
      preLoaderRoute: typeof ApiSkillsNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills/$name/files/$': {
      id: '/api/skills/$name/files/$'
      path: '/api/skills/$name/files/$'
      fullPath: '/api/skills/$name/files/$'
      preLoaderRoute: typeof ApiSkillsNameFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiInstallCliRoute: ApiInstallCliRoute,
  ApiInstallShRoute: ApiInstallShRoute,
  ApiSkillsIndexRoute: ApiSkillsIndexRoute,
  ApiSkillsNameIndexRoute: ApiSkillsNameIndexRoute,
  ApiSkillsNameFilesSplatRoute: ApiSkillsNameFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
