export type ComponentCategory =
  | "Form"
  | "Navigation"
  | "Overlay"
  | "Feedback"
  | "Display"
  | "AI"
  | "Composition";

export type ComponentRecord = {
  id: string;
  title: string;
  category: ComponentCategory;
  primitive: string;
  files: string[];
  figmaSource: string;
  description: string;
  custom: boolean;
};

export const componentCatalog = [
  {
    id: "accordion",
    title: "Accordion",
    category: "Navigation",
    primitive: "Accordion, AccordionItem, AccordionTrigger, AccordionContent",
    files: ["src/components/ui/accordion.tsx"],
    figmaSource: "Accordion / Standard Accordion / Progress Accordion",
    description: "Base UI accordion restyled to the compact Medusa card row.",
    custom: false,
  },
  {
    id: "ai-assistant",
    title: "AI Assistant",
    category: "AI",
    primitive: "Button, Avatar, Badge, Command, Prompt, ChatBlock",
    files: [
      "src/components/ui/button.tsx",
      "src/components/ui/avatar.tsx",
      "src/components/ui/command.tsx",
      "src/components/design/prompt-kit.tsx",
    ],
    figmaSource: "Medusa compact surfaces plus Prompt Kit primitives",
    description: "A composed assistant panel using shadcn primitives and Prompt Kit style anatomy.",
    custom: true,
  },
  {
    id: "alert",
    title: "Alert",
    category: "Feedback",
    primitive: "Alert, AlertTitle, AlertDescription, AlertAction",
    files: ["src/components/ui/alert.tsx"],
    figmaSource: "Medusa card-rest elevation and compact text tokens",
    description: "Status messaging with compact type and a subtle action slot.",
    custom: false,
  },
  {
    id: "avatar",
    title: "Avatar",
    category: "Display",
    primitive: "Avatar, AvatarImage, AvatarFallback, AvatarBadge, AvatarGroup",
    files: ["src/components/ui/avatar.tsx"],
    figmaSource: "Medusa icon and item density",
    description: "Profile identity primitives for user rows and chat items.",
    custom: false,
  },
  {
    id: "badge",
    title: "Badge",
    category: "Display",
    primitive: "Badge",
    files: ["src/components/ui/badge.tsx"],
    figmaSource: "Medusa compact label token",
    description: "Small status tags mapped to Medusa border and text tokens.",
    custom: false,
  },
  {
    id: "breadcrumbs",
    title: "Breadcrumbs",
    category: "Navigation",
    primitive: "Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage",
    files: ["src/components/ui/breadcrumb.tsx"],
    figmaSource: "File info / Path",
    description: "The docs path row from the Figma file, mapped to shadcn breadcrumb primitives.",
    custom: false,
  },
  {
    id: "button",
    title: "Button",
    category: "Form",
    primitive: "Button",
    files: ["src/components/ui/button.tsx"],
    figmaSource: "Button base token references in Medusa file headers",
    description: "Primary action, outline action, ghost action, and icon-only sizes.",
    custom: false,
  },
  {
    id: "button-group",
    title: "Button Group",
    category: "Form",
    primitive: "ButtonGroup, ButtonGroupText, ButtonGroupSeparator",
    files: ["src/components/ui/button-group.tsx", "src/components/ui/button.tsx"],
    figmaSource: "Compact grouped control density",
    description: "Grouped actions with shared borders and separator support.",
    custom: false,
  },
  {
    id: "checkbox",
    title: "Checkbox",
    category: "Form",
    primitive: "Checkbox",
    files: ["src/components/ui/checkbox.tsx", "src/components/ui/field.tsx"],
    figmaSource: "Progress indicator sizing and compact field text",
    description: "Boolean control inside Field anatomy.",
    custom: false,
  },
  {
    id: "chat",
    title: "Chat",
    category: "AI",
    primitive: "Chat, ChatMessage, PromptInput",
    files: ["src/components/design/prompt-kit.tsx"],
    figmaSource: "Medusa cards plus Prompt Kit Message and ChatContainer anatomy",
    description: "A local chat composition with messages, avatars, actions, and composer.",
    custom: true,
  },
  {
    id: "chat-blocks",
    title: "Chat Blocks",
    category: "AI",
    primitive: "ChatBlock, ChatBlockHeader, ChatBlockContent",
    files: ["src/components/design/prompt-kit.tsx", "src/components/ui/card.tsx"],
    figmaSource: "Medusa card-rest elevation",
    description: "Structured AI output blocks for tool results and summaries.",
    custom: true,
  },
  {
    id: "chat-items",
    title: "Chat Items",
    category: "AI",
    primitive: "ChatMessage, Item, Avatar",
    files: ["src/components/design/prompt-kit.tsx", "src/components/ui/item.tsx"],
    figmaSource: "Item rows and compact message type",
    description: "Message row anatomy built from Avatar and Item-like content slots.",
    custom: true,
  },
  {
    id: "code",
    title: "Code",
    category: "Display",
    primitive: "Code",
    files: ["src/components/design/code.tsx"],
    figmaSource: "Code Labels/code-label-xsmall",
    description: "Inline code token aligned to Medusa monospace labels.",
    custom: true,
  },
  {
    id: "code-block",
    title: "Code Block",
    category: "Display",
    primitive: "CodeBlock, Code",
    files: ["src/components/design/code.tsx", "src/components/ui/button.tsx"],
    figmaSource: "Code label token plus card-rest elevation",
    description: "Prompt Kit style code block with a compact header and copy action.",
    custom: true,
  },
  {
    id: "commandbar",
    title: "Commandbar",
    category: "Overlay",
    primitive: "Command, CommandInput, CommandList, CommandItem",
    files: ["src/components/ui/command.tsx"],
    figmaSource: "Medusa popover surface and compact rows",
    description: "Command palette primitives styled as a Medusa commandbar.",
    custom: false,
  },
  {
    id: "separator",
    title: "Separator",
    category: "Display",
    primitive: "Separator",
    files: ["src/components/ui/separator.tsx"],
    figmaSource: "Content Divider",
    description: "Line and dotted separators matching the Figma divider page.",
    custom: false,
  },
  {
    id: "date-picker",
    title: "Date Picker",
    category: "Form",
    primitive: "DatePicker = Popover + Button + Calendar",
    files: ["src/components/design/form-compositions.tsx", "src/components/ui/calendar.tsx"],
    figmaSource: "Medusa compact popover and control tokens",
    description: "Local wrapper around the official Calendar primitive.",
    custom: true,
  },
  {
    id: "filter",
    title: "Filter",
    category: "Composition",
    primitive: "FilterPanel = Popover + Select + Checkbox + Badge",
    files: ["src/components/design/form-compositions.tsx"],
    figmaSource: "Medusa compact popover and grouped fields",
    description: "A composed filter surface for table and search flows.",
    custom: true,
  },
  {
    id: "hovercard",
    title: "Hover Card",
    category: "Overlay",
    primitive: "HoverCard, HoverCardTrigger, HoverCardContent",
    files: ["src/components/ui/hover-card.tsx"],
    figmaSource: "Medusa card-rest elevation",
    description: "Preview card on hover with the same compact surface model.",
    custom: false,
  },
  {
    id: "input",
    title: "Input",
    category: "Form",
    primitive: "Input, InputGroup, InputGroupInput, Textarea",
    files: ["src/components/ui/input.tsx", "src/components/ui/input-group.tsx"],
    figmaSource: "Medusa compact controls",
    description: "Text entry primitives with prefix, suffix, and textarea variants.",
    custom: false,
  },
  {
    id: "item-block",
    title: "Item Block",
    category: "Display",
    primitive: "Item, ItemMedia, ItemContent, Card",
    files: ["src/components/ui/item.tsx", "src/components/ui/card.tsx"],
    figmaSource: "Medusa item/card surfaces",
    description: "A card-backed item block for rows, settings, and summaries.",
    custom: false,
  },
  {
    id: "kbd",
    title: "Kbd",
    category: "Display",
    primitive: "Kbd, KbdGroup",
    files: ["src/components/ui/kbd.tsx"],
    figmaSource: "Compact label and border tokens",
    description: "Keyboard shortcut display with grouped keys.",
    custom: false,
  },
  {
    id: "label",
    title: "Label",
    category: "Form",
    primitive: "Label, FieldLabel",
    files: ["src/components/ui/label.tsx", "src/components/ui/field.tsx"],
    figmaSource: "Labels/txt-compact-small-plus",
    description: "Field label text aligned to Medusa compact plus.",
    custom: false,
  },
  {
    id: "menu",
    title: "Menu",
    category: "Overlay",
    primitive: "DropdownMenu and Menubar",
    files: ["src/components/ui/dropdown-menu.tsx", "src/components/ui/menubar.tsx"],
    figmaSource: "Medusa popover and compact item rows",
    description: "Action menus and top-level menubars backed by Base UI menu primitives.",
    custom: false,
  },
  {
    id: "modal",
    title: "Modal",
    category: "Overlay",
    primitive: "Dialog, DialogContent, DialogTitle",
    files: ["src/components/ui/dialog.tsx"],
    figmaSource: "Medusa card-rest elevation and compact fields",
    description: "Dialog mapped to the requested modal naming.",
    custom: false,
  },
  {
    id: "prompt",
    title: "Prompt",
    category: "AI",
    primitive: "PromptInput, PromptToolbar, PromptSuggestion",
    files: ["src/components/design/prompt-kit.tsx"],
    figmaSource: "Medusa input/card tokens plus Prompt Kit PromptInput anatomy",
    description: "Local prompt composer with action rail and suggestions.",
    custom: true,
  },
  {
    id: "popover",
    title: "Popover",
    category: "Overlay",
    primitive: "Popover, PopoverTrigger, PopoverContent",
    files: ["src/components/ui/popover.tsx"],
    figmaSource: "Medusa card-rest elevation",
    description: "Floating content with title and description slots.",
    custom: false,
  },
  {
    id: "radio",
    title: "Radio Group",
    category: "Form",
    primitive: "RadioGroup, RadioGroupItem",
    files: ["src/components/ui/radio-group.tsx"],
    figmaSource: "Progress indicator size and compact field labels",
    description: "Radio and radio group examples.",
    custom: false,
  },
  {
    id: "segmented-control",
    title: "Segmented Control",
    category: "Form",
    primitive: "ToggleGroup, ToggleGroupItem",
    files: ["src/components/ui/toggle-group.tsx"],
    figmaSource: "Medusa grouped control surface",
    description: "Segmented choices mapped to ToggleGroup.",
    custom: false,
  },
  {
    id: "select",
    title: "Select",
    category: "Form",
    primitive: "Select, SelectTrigger, SelectContent, SelectItem",
    files: ["src/components/ui/select.tsx"],
    figmaSource: "Medusa compact controls and menu rows",
    description: "Select menus with grouped items.",
    custom: false,
  },
  {
    id: "search",
    title: "Search",
    category: "Form",
    primitive: "SearchInput = InputGroup + Input",
    files: ["src/components/design/form-compositions.tsx"],
    figmaSource: "Medusa compact input and icon sizing",
    description: "An input variant, composed with InputGroup.",
    custom: true,
  },
  {
    id: "switch",
    title: "Switch",
    category: "Form",
    primitive: "Switch",
    files: ["src/components/ui/switch.tsx"],
    figmaSource: "Medusa compact control scale",
    description: "Binary toggle with Field label support.",
    custom: false,
  },
  {
    id: "table",
    title: "Table",
    category: "Display",
    primitive: "Table, TableHeader, TableBody, TableRow, TableCell",
    files: ["src/components/ui/table.tsx"],
    figmaSource: "Medusa grid lines and code labels",
    description: "Data table with compact rows and understated dividers.",
    custom: false,
  },
  {
    id: "tabs",
    title: "Tabs",
    category: "Navigation",
    primitive: "Tabs, TabsList, TabsTrigger, TabsContent",
    files: ["src/components/ui/tabs.tsx"],
    figmaSource: "Medusa grouped control surface",
    description: "Tabbed interface styled as a compact segmented rail.",
    custom: false,
  },
  {
    id: "toast",
    title: "Toast",
    category: "Feedback",
    primitive: "Toaster and toast() from sonner",
    files: ["src/components/ui/sonner.tsx"],
    figmaSource: "Medusa card-rest elevation",
    description: "Sonner toast surface aligned to Medusa tokens.",
    custom: false,
  },
  {
    id: "tooltip",
    title: "Tooltip",
    category: "Overlay",
    primitive: "Tooltip, TooltipTrigger, TooltipContent",
    files: ["src/components/ui/tooltip.tsx"],
    figmaSource: "Medusa compact overlay text",
    description: "Small contextual overlay for compact icon controls.",
    custom: false,
  },
] satisfies ComponentRecord[];

export const catalogById = Object.fromEntries(
  componentCatalog.map((component) => [component.id, component]),
) as Record<string, ComponentRecord>;

export const featuredComponentIds = [
  "accordion",
  "button",
  "prompt",
  "chat",
  "date-picker",
  "table",
];
