export type ComponentCategory = "Components" | "Blocks";

export type ComponentRecord = {
  id: string;
  title: string;
  category: ComponentCategory;
  primitive: string;
  files: string[];
  figmaSource: string;
  description: string;
  custom: boolean;
};

export const componentCatalog = [
  {
    id: "accordion",
    title: "Accordion",
    category: "Components",
    primitive: "Accordion, AccordionItem, AccordionTrigger, AccordionContent",
    files: ["src/components/ui/accordion.tsx"],
    figmaSource: "Accordion / Standard Accordion / Progress Accordion",
    description: "Base UI accordion restyled as a compact card row.",
    custom: false,
  },
  {
    id: "message-composer",
    title: "Message Composer",
    category: "Blocks",
    primitive: "MessageComposer",
    files: [
      "src/components/ui/button.tsx",
      "src/components/design/message-composer.tsx",
    ],
    figmaSource: "Puch app message composer",
    description:
      "A composed chat input bar with multiline and attachment states.",
    custom: true,
  },
  {
    id: "command-palette",
    title: "Command Palette",
    category: "Blocks",
    primitive: "DocsSearch",
    files: [
      "src/components/design/docs-search.tsx",
      "src/lib/docs-search.ts",
      "src/components/ui/command.tsx",
      "src/components/ui/dialog.tsx",
    ],
    figmaSource: "Raycast-style command palette reference",
    description:
      "Site-wide docs search palette with keyboard actions for selected results.",
    custom: true,
  },
  {
    id: "dynamic-island",
    title: "Dynamic Island",
    category: "Blocks",
    primitive: "DynamicIsland",
    files: ["src/components/design/dynamic-island.tsx"],
    figmaSource: "Dynamic Island motion recreation",
    description: "A Motion recreation of Dynamic Island view morphing.",
    custom: true,
  },
  {
    id: "family-drawer",
    title: "Family Drawer",
    category: "Blocks",
    primitive: "FamilyDrawer",
    files: ["src/components/design/family-drawer.tsx"],
    figmaSource: "Family drawer motion recreation",
    description: "A Motion recreation of the Family-style floating drawer.",
    custom: true,
  },
  {
    id: "alert",
    title: "Alert",
    category: "Components",
    primitive: "Alert, AlertTitle, AlertDescription, AlertAction",
    files: ["src/components/ui/alert.tsx"],
    figmaSource: "Card-rest elevation and compact text tokens",
    description: "Status messaging with compact type and a subtle action slot.",
    custom: false,
  },
  {
    id: "avatar",
    title: "Avatar",
    category: "Components",
    primitive: "Avatar, AvatarImage, AvatarFallback, AvatarBadge, AvatarGroup",
    files: ["src/components/ui/avatar.tsx"],
    figmaSource: "Icon and item density",
    description:
      "Profile identity primitives for user rows and compact item surfaces.",
    custom: false,
  },
  {
    id: "badge",
    title: "Badge",
    category: "Components",
    primitive: "Badge",
    files: ["src/components/ui/badge.tsx"],
    figmaSource: "Compact label token",
    description: "Small status tags mapped to border and text tokens.",
    custom: false,
  },
  {
    id: "breadcrumbs",
    title: "Breadcrumbs",
    category: "Components",
    primitive:
      "Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage",
    files: ["src/components/ui/breadcrumb.tsx"],
    figmaSource: "File info / Path",
    description:
      "The docs path row from the Figma file, mapped to shadcn breadcrumb primitives.",
    custom: false,
  },
  {
    id: "button",
    title: "Button",
    category: "Components",
    primitive: "Button",
    files: ["src/components/ui/button.tsx"],
    figmaSource: "Button base token references in Figma file headers",
    description:
      "Primary action, outline action, ghost action, and icon-only sizes.",
    custom: false,
  },
  {
    id: "button-group",
    title: "Button Group",
    category: "Components",
    primitive: "ButtonGroup, ButtonGroupText, ButtonGroupSeparator",
    files: [
      "src/components/ui/button-group.tsx",
      "src/components/ui/button.tsx",
    ],
    figmaSource: "Compact grouped control density",
    description: "Grouped actions with shared borders and separator support.",
    custom: false,
  },
  {
    id: "card",
    title: "Card",
    category: "Components",
    primitive:
      "Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter",
    files: ["src/components/ui/card.tsx"],
    figmaSource: "Modal/card-rest elevation",
    description: "Static modal-like surface for grouped content and actions.",
    custom: false,
  },
  {
    id: "calendar",
    title: "Calendar",
    category: "Components",
    primitive: "Calendar, CalendarDayButton",
    files: ["src/components/ui/calendar.tsx"],
    figmaSource: "Compact calendar popover tokens",
    description:
      "React DayPicker primitive with compact density, range states, and composition examples.",
    custom: false,
  },
  {
    id: "checkbox",
    title: "Checkbox",
    category: "Components",
    primitive: "Checkbox",
    files: ["src/components/ui/checkbox.tsx", "src/components/ui/field.tsx"],
    figmaSource: "Progress indicator sizing and compact field text",
    description: "Boolean control inside Field anatomy.",
    custom: false,
  },
  {
    id: "combobox",
    title: "Combobox",
    category: "Components",
    primitive:
      "Combobox, ComboboxInput, ComboboxContent, ComboboxItem, ComboboxChips, ComboboxChip",
    files: ["src/components/ui/combobox.tsx"],
    figmaSource: "Single / multiselect and select menu",
    description: "Searchable select with optional multiselect chips.",
    custom: false,
  },
  {
    id: "code",
    title: "Code",
    category: "Components",
    primitive: "Code",
    files: ["src/components/design/code.tsx"],
    figmaSource: "Code Labels/code-label-xsmall",
    description: "Inline code token aligned to compact monospace labels.",
    custom: true,
  },
  {
    id: "code-block",
    title: "Code Block",
    category: "Components",
    primitive: "CodeBlock, Code",
    files: ["src/components/design/code.tsx", "src/components/ui/button.tsx"],
    figmaSource: "Code label token plus card-rest elevation",
    description:
      "Prompt Kit style code block with a compact header and copy action.",
    custom: true,
  },
  {
    id: "commandbar",
    title: "Commandbar",
    category: "Components",
    primitive: "CommandBar, CommandBarAction",
    files: ["src/components/ui/command.tsx"],
    figmaSource: "Popover surface and compact rows",
    description: "Floating toolbar for bulk actions and selected states.",
    custom: false,
  },
  {
    id: "separator",
    title: "Separator",
    category: "Components",
    primitive: "Separator",
    files: ["src/components/ui/separator.tsx"],
    figmaSource: "Content Divider",
    description: "Line and dotted separators matching the Figma divider page.",
    custom: false,
  },
  {
    id: "hovercard",
    title: "Hover Card",
    category: "Components",
    primitive: "HoverCard, HoverCardTrigger, HoverCardContent",
    files: ["src/components/ui/hover-card.tsx"],
    figmaSource: "Card-rest elevation",
    description: "Preview card on hover with the same compact surface model.",
    custom: false,
  },
  {
    id: "input",
    title: "Input",
    category: "Components",
    primitive: "Input, InputGroup, InputGroupInput, Textarea",
    files: ["src/components/ui/input.tsx", "src/components/ui/input-group.tsx"],
    figmaSource: "Compact controls",
    description:
      "Text entry primitives with prefix, suffix, and textarea variants.",
    custom: false,
  },
  {
    id: "kbd",
    title: "Kbd",
    category: "Components",
    primitive: "Kbd, KbdGroup",
    files: ["src/components/ui/kbd.tsx"],
    figmaSource: "Compact label and border tokens",
    description: "Keyboard shortcut display with grouped keys.",
    custom: false,
  },
  {
    id: "label",
    title: "Label",
    category: "Components",
    primitive: "Label, FieldLabel",
    files: ["src/components/ui/label.tsx", "src/components/ui/field.tsx"],
    figmaSource: "Labels/txt-compact-small-plus",
    description: "Field label text aligned to compact plus.",
    custom: false,
  },
  {
    id: "menu",
    title: "Menu",
    category: "Components",
    primitive: "DropdownMenu and Menubar",
    files: [
      "src/components/ui/dropdown-menu.tsx",
      "src/components/ui/menubar.tsx",
    ],
    figmaSource: "Popover and compact item rows",
    description:
      "Action menus and top-level menubars backed by Base UI menu primitives.",
    custom: false,
  },
  {
    id: "modal",
    title: "Modal",
    category: "Components",
    primitive: "Dialog, DialogContent, DialogTitle",
    files: ["src/components/ui/dialog.tsx"],
    figmaSource: "Card-rest elevation and compact fields",
    description: "Dialog mapped to the requested modal naming.",
    custom: false,
  },
  {
    id: "popover",
    title: "Popover",
    category: "Components",
    primitive: "Popover, PopoverTrigger, PopoverContent",
    files: ["src/components/ui/popover.tsx"],
    figmaSource: "Card-rest elevation",
    description: "Floating content with title and description slots.",
    custom: false,
  },
  {
    id: "radio",
    title: "Radio Group",
    category: "Components",
    primitive: "RadioGroup, RadioGroupItem",
    files: ["src/components/ui/radio-group.tsx"],
    figmaSource: "Progress indicator size and compact field labels",
    description: "Radio and radio group examples.",
    custom: false,
  },
  {
    id: "select",
    title: "Select",
    category: "Components",
    primitive: "Select, SelectTrigger, SelectContent, SelectItem",
    files: ["src/components/ui/select.tsx"],
    figmaSource: "Compact controls and menu rows",
    description: "Select menus with grouped items.",
    custom: false,
  },
  {
    id: "search",
    title: "Search",
    category: "Components",
    primitive: "SearchInput = InputGroup + Input, SearchModal = Command",
    files: [
      "src/components/ui/input-group.tsx",
      "src/components/ui/command.tsx",
    ],
    figmaSource: "Compact input and icon sizing",
    description:
      "Search input variants plus the command-style search modal.",
    custom: true,
  },
  {
    id: "switch",
    title: "Switch",
    category: "Components",
    primitive: "Switch",
    files: ["src/components/ui/switch.tsx"],
    figmaSource: "Compact control scale",
    description: "Binary toggle with Field label support.",
    custom: false,
  },
  {
    id: "table",
    title: "Table",
    category: "Components",
    primitive: "Table, TableHeader, TableBody, TableRow, TableCell",
    files: ["src/components/ui/table.tsx"],
    figmaSource: "Grid lines and code labels",
    description: "Data table with compact rows and understated dividers.",
    custom: false,
  },
  {
    id: "tabs",
    title: "Tabs",
    category: "Components",
    primitive: "Tabs, TabsList, TabsTrigger, TabsContent",
    files: ["src/components/ui/tabs.tsx"],
    figmaSource: "Grouped control surface",
    description: "Tabbed interface styled as a compact segmented rail.",
    custom: false,
  },
  {
    id: "toast",
    title: "Toast",
    category: "Components",
    primitive: "Toaster and toast() from sonner",
    files: ["src/components/ui/sonner.tsx"],
    figmaSource: "Card-rest elevation",
    description: "Sonner toast surface aligned to local tokens.",
    custom: false,
  },
  {
    id: "tooltip",
    title: "Tooltip",
    category: "Components",
    primitive: "Tooltip, TooltipTrigger, TooltipContent",
    files: ["src/components/ui/tooltip.tsx"],
    figmaSource: "Compact overlay text",
    description: "Small contextual overlay for compact icon controls.",
    custom: false,
  },
] satisfies ComponentRecord[];

export const catalogById = Object.fromEntries(
  componentCatalog.map((component) => [component.id, component]),
) as Record<string, ComponentRecord>;

export const featuredComponentIds = [
  "accordion",
  "button",
  "message-composer",
  "calendar",
  "table",
];
