export type ComponentCategory = "Components" | "Blocks";

export type ComponentRecord = {
  id: string;
  title: string;
  category: ComponentCategory;
  primitive: string;
  files: string[];
  figmaSource: string;
  description: string;
  custom: boolean;
};

export const componentCatalog = [
  {
    id: "accordion",
    title: "Accordion",
    category: "Components",
    primitive: "Accordion, AccordionItem, AccordionTrigger, AccordionContent",
    files: ["src/components/ui/accordion.tsx"],
    figmaSource: "Accordion / Standard Accordion / Progress Accordion",
    description: "Base UI accordion restyled to the compact Medusa card row.",
    custom: false,
  },
  {
    id: "ai-assistant",
    title: "AI Assistant",
    category: "Blocks",
    primitive: "AIAssistant",
    files: [
      "src/components/ui/button.tsx",
      "src/components/ui/avatar.tsx",
      "src/components/ui/command.tsx",
      "src/components/design/ai-assistant.tsx",
    ],
    figmaSource: "Medusa compact assistant block",
    description: "A composed assistant panel built from Medusa UI primitives.",
    custom: true,
  },
  {
    id: "alert",
    title: "Alert",
    category: "Components",
    primitive: "Alert, AlertTitle, AlertDescription, AlertAction",
    files: ["src/components/ui/alert.tsx"],
    figmaSource: "Medusa card-rest elevation and compact text tokens",
    description: "Status messaging with compact type and a subtle action slot.",
    custom: false,
  },
  {
    id: "avatar",
    title: "Avatar",
    category: "Components",
    primitive: "Avatar, AvatarImage, AvatarFallback, AvatarBadge, AvatarGroup",
    files: ["src/components/ui/avatar.tsx"],
    figmaSource: "Medusa icon and item density",
    description:
      "Profile identity primitives for user rows and compact item surfaces.",
    custom: false,
  },
  {
    id: "badge",
    title: "Badge",
    category: "Components",
    primitive: "Badge",
    files: ["src/components/ui/badge.tsx"],
    figmaSource: "Medusa compact label token",
    description: "Small status tags mapped to Medusa border and text tokens.",
    custom: false,
  },
  {
    id: "breadcrumbs",
    title: "Breadcrumbs",
    category: "Components",
    primitive:
      "Breadcrumb, BreadcrumbList, BreadcrumbItem, BreadcrumbLink, BreadcrumbPage",
    files: ["src/components/ui/breadcrumb.tsx"],
    figmaSource: "File info / Path",
    description:
      "The docs path row from the Figma file, mapped to shadcn breadcrumb primitives.",
    custom: false,
  },
  {
    id: "button",
    title: "Button",
    category: "Components",
    primitive: "Button",
    files: ["src/components/ui/button.tsx"],
    figmaSource: "Button base token references in Medusa file headers",
    description:
      "Primary action, outline action, ghost action, and icon-only sizes.",
    custom: false,
  },
  {
    id: "button-group",
    title: "Button Group",
    category: "Components",
    primitive: "ButtonGroup, ButtonGroupText, ButtonGroupSeparator",
    files: [
      "src/components/ui/button-group.tsx",
      "src/components/ui/button.tsx",
    ],
    figmaSource: "Compact grouped control density",
    description: "Grouped actions with shared borders and separator support.",
    custom: false,
  },
  {
    id: "checkbox",
    title: "Checkbox",
    category: "Components",
    primitive: "Checkbox",
    files: ["src/components/ui/checkbox.tsx", "src/components/ui/field.tsx"],
    figmaSource: "Progress indicator sizing and compact field text",
    description: "Boolean control inside Field anatomy.",
    custom: false,
  },
  {
    id: "combobox",
    title: "Combobox",
    category: "Components",
    primitive:
      "Combobox, ComboboxInput, ComboboxContent, ComboboxItem, ComboboxChips, ComboboxChip",
    files: ["src/components/ui/combobox.tsx"],
    figmaSource: "Medusa single / multiselect and select menu",
    description: "Searchable select with optional multiselect chips.",
    custom: false,
  },
  {
    id: "code",
    title: "Code",
    category: "Components",
    primitive: "Code",
    files: ["src/components/design/code.tsx"],
    figmaSource: "Code Labels/code-label-xsmall",
    description: "Inline code token aligned to Medusa monospace labels.",
    custom: true,
  },
  {
    id: "code-block",
    title: "Code Block",
    category: "Components",
    primitive: "CodeBlock, Code",
    files: ["src/components/design/code.tsx", "src/components/ui/button.tsx"],
    figmaSource: "Code label token plus card-rest elevation",
    description:
      "Prompt Kit style code block with a compact header and copy action.",
    custom: true,
  },
  {
    id: "commandbar",
    title: "Commandbar",
    category: "Components",
    primitive: "Command, CommandInput, CommandList, CommandItem",
    files: ["src/components/ui/command.tsx"],
    figmaSource: "Medusa popover surface and compact rows",
    description: "Command palette primitives styled as a Medusa commandbar.",
    custom: false,
  },
  {
    id: "separator",
    title: "Separator",
    category: "Components",
    primitive: "Separator",
    files: ["src/components/ui/separator.tsx"],
    figmaSource: "Content Divider",
    description: "Line and dotted separators matching the Figma divider page.",
    custom: false,
  },
  {
    id: "date-picker",
    title: "Date Picker",
    category: "Components",
    primitive: "DatePicker = Popover + Button + Calendar",
    files: [
      "src/components/design/form-compositions.tsx",
      "src/components/ui/calendar.tsx",
    ],
    figmaSource: "Medusa compact popover and control tokens",
    description: "Local wrapper around the official Calendar primitive.",
    custom: true,
  },
  {
    id: "hovercard",
    title: "Hover Card",
    category: "Components",
    primitive: "HoverCard, HoverCardTrigger, HoverCardContent",
    files: ["src/components/ui/hover-card.tsx"],
    figmaSource: "Medusa card-rest elevation",
    description: "Preview card on hover with the same compact surface model.",
    custom: false,
  },
  {
    id: "input",
    title: "Input",
    category: "Components",
    primitive: "Input, InputGroup, InputGroupInput, Textarea",
    files: ["src/components/ui/input.tsx", "src/components/ui/input-group.tsx"],
    figmaSource: "Medusa compact controls",
    description:
      "Text entry primitives with prefix, suffix, and textarea variants.",
    custom: false,
  },
  {
    id: "item-block",
    title: "Item Block",
    category: "Components",
    primitive: "Item, ItemMedia, ItemContent, Card",
    files: ["src/components/ui/item.tsx", "src/components/ui/card.tsx"],
    figmaSource: "Medusa item/card surfaces",
    description: "A card-backed item block for rows, settings, and summaries.",
    custom: false,
  },
  {
    id: "kbd",
    title: "Kbd",
    category: "Components",
    primitive: "Kbd, KbdGroup",
    files: ["src/components/ui/kbd.tsx"],
    figmaSource: "Compact label and border tokens",
    description: "Keyboard shortcut display with grouped keys.",
    custom: false,
  },
  {
    id: "label",
    title: "Label",
    category: "Components",
    primitive: "Label, FieldLabel",
    files: ["src/components/ui/label.tsx", "src/components/ui/field.tsx"],
    figmaSource: "Labels/txt-compact-small-plus",
    description: "Field label text aligned to Medusa compact plus.",
    custom: false,
  },
  {
    id: "menu",
    title: "Menu",
    category: "Components",
    primitive: "DropdownMenu and Menubar",
    files: [
      "src/components/ui/dropdown-menu.tsx",
      "src/components/ui/menubar.tsx",
    ],
    figmaSource: "Medusa popover and compact item rows",
    description:
      "Action menus and top-level menubars backed by Base UI menu primitives.",
    custom: false,
  },
  {
    id: "modal",
    title: "Modal",
    category: "Components",
    primitive: "Dialog, DialogContent, DialogTitle",
    files: ["src/components/ui/dialog.tsx"],
    figmaSource: "Medusa card-rest elevation and compact fields",
    description: "Dialog mapped to the requested modal naming.",
    custom: false,
  },
  {
    id: "popover",
    title: "Popover",
    category: "Components",
    primitive: "Popover, PopoverTrigger, PopoverContent",
    files: ["src/components/ui/popover.tsx"],
    figmaSource: "Medusa card-rest elevation",
    description: "Floating content with title and description slots.",
    custom: false,
  },
  {
    id: "radio",
    title: "Radio Group",
    category: "Components",
    primitive: "RadioGroup, RadioGroupItem",
    files: ["src/components/ui/radio-group.tsx"],
    figmaSource: "Progress indicator size and compact field labels",
    description: "Radio and radio group examples.",
    custom: false,
  },
  {
    id: "select",
    title: "Select",
    category: "Components",
    primitive: "Select, SelectTrigger, SelectContent, SelectItem",
    files: ["src/components/ui/select.tsx"],
    figmaSource: "Medusa compact controls and menu rows",
    description: "Select menus with grouped items.",
    custom: false,
  },
  {
    id: "search",
    title: "Search",
    category: "Components",
    primitive: "SearchInput = InputGroup + Input, SearchModal = Command",
    files: [
      "src/components/ui/input-group.tsx",
      "src/components/ui/command.tsx",
    ],
    figmaSource: "Medusa compact input and icon sizing",
    description:
      "Search input variants plus the Medusa command-style search modal.",
    custom: true,
  },
  {
    id: "switch",
    title: "Switch",
    category: "Components",
    primitive: "Switch",
    files: ["src/components/ui/switch.tsx"],
    figmaSource: "Medusa compact control scale",
    description: "Binary toggle with Field label support.",
    custom: false,
  },
  {
    id: "table",
    title: "Table",
    category: "Components",
    primitive: "Table, TableHeader, TableBody, TableRow, TableCell",
    files: ["src/components/ui/table.tsx"],
    figmaSource: "Medusa grid lines and code labels",
    description: "Data table with compact rows and understated dividers.",
    custom: false,
  },
  {
    id: "tabs",
    title: "Tabs",
    category: "Components",
    primitive: "Tabs, TabsList, TabsTrigger, TabsContent",
    files: ["src/components/ui/tabs.tsx"],
    figmaSource: "Medusa grouped control surface",
    description: "Tabbed interface styled as a compact segmented rail.",
    custom: false,
  },
  {
    id: "toast",
    title: "Toast",
    category: "Components",
    primitive: "Toaster and toast() from sonner",
    files: ["src/components/ui/sonner.tsx"],
    figmaSource: "Medusa card-rest elevation",
    description: "Sonner toast surface aligned to Medusa tokens.",
    custom: false,
  },
  {
    id: "tooltip",
    title: "Tooltip",
    category: "Components",
    primitive: "Tooltip, TooltipTrigger, TooltipContent",
    files: ["src/components/ui/tooltip.tsx"],
    figmaSource: "Medusa compact overlay text",
    description: "Small contextual overlay for compact icon controls.",
    custom: false,
  },
] satisfies ComponentRecord[];

export const catalogById = Object.fromEntries(
  componentCatalog.map((component) => [component.id, component]),
) as Record<string, ComponentRecord>;

export const featuredComponentIds = [
  "accordion",
  "button",
  "ai-assistant",
  "date-picker",
  "table",
];
